#!/bin/bash
# The interpreter used to execute the script
# "#SBATCH" directives that convey submission options:
#SBATCH --job-name=camo_train
#SBATCH --mail-user=edwinpa@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m
#SBATCH --time=01:00:00
#SBATCH --account=eecs442f25_class
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1 
#SBATCH --output=test.log
module load python/3.12.1
source ~/envs/camo/bin/activate
python test.py